config/routes.rb
IPManagement::Application.routes.draw do
  resources :ip_addr_usages
  resources :available_ip_addresses, only: [:create, :destroy]

  root 'ip_addr_usages#index'
  match '/config', to: 'available_ip_addresses#configure', via: 'get'

  

end

app/models/available_ip_address.rb
class AvailableIpAddress < ActiveRecord::Base
  has_one :ip_addr_usage, dependent: :restrict_with_exception

  validates :ip_address, ip_addr: true, presence: true,
                         uniqueness: true

  def <=>(rhs)
    lhs_operand = ip_address.split('.').map { |i| "%3d" % i.to_i }
    rhs_operand = rhs.ip_address.split('.').map { |i| "%3d" % i.to_i }
    lhs_operand <=> rhs_operand
  end

  def AvailableIpAddress.unused
    all.select{ |addr| addr.ip_addr_usage.nil? }
  end
end

app/models/configure_form.rb
class ConfigureForm
  include ActiveModel::Model
  include ActiveModel::Validations

  attr_accessor :ip_addr_single
  attr_accessor :ip_addr_start, :ip_addr_end

  validates :ip_addr_single, ip_addr_or_blank: true
  validates :ip_addr_start, ip_addr_or_blank: true
  validates :ip_addr_end, ip_addr_or_blank: true
end

app/models/ip_addr_or_blank_validator.rb
# coding: utf-8

class IpAddrOrBlankValidator < ActiveModel::EachValidator
  def validate_each( record, attribute, value )
    unless value =~ Resolv::IPv4::Regex or value =~ Resolv::IPv6::Regex or value.blank?
      record.errors.add(attribute, 'is not IP address nor blank')
    end
  end
end

app/models/ip_addr_usage.rb
class IpAddrUsage < ActiveRecord::Base
  belongs_to :available_ip_address 
  validates :user, presence: true
  validates :location, presence: true
  validates :available_ip_address_id, presence: true,
                         uniqueness: true

  def ip_address
    self.available_ip_address.ip_address 
  end

  def <=>(rhs)
    available_ip_address <=> rhs.available_ip_address
  end

  # ping_failure_countの状態を表すbootstrapのCSSクラスを戻す
  def status
    case ping_failure_count
    when 0
      ""
    when 1...THRESHOLD
      "text-warning"
    else
      "text-error"
    end
  end

  # ping到達不能を示す閾値
  THRESHOLD = 7
  scope :unreachable, where("ping_failure_count >= ?", THRESHOLD)
end

app/models/ip_addr_validator.rb
# coding: utf-8

class IpAddrValidator < ActiveModel::EachValidator
  def validate_each( record, attribute, value )
    unless value =~ Resolv::IPv4::Regex or value =~ Resolv::IPv6::Regex
      record.errors.add(attribute, 'is not IP address')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/available_ip_addresses_controller.rb
class AvailableIpAddressesController < ApplicationController
  def configure
    @configure_form = ConfigureForm.new
    @addresses = AvailableIpAddress.all
  end

  def create
    @configure_form = ConfigureForm.new(params[:configure_form])
    @configure_form.valid?
    @new_address = AvailableIpAddress.new
    if are_single_and_range_forms_filled(@configure_form)
      flash[:failure] = "unavailable at the same time range registration and registration alone"

    elsif not @configure_form.ip_addr_single.blank?
      if AvailableIpAddress.new(ip_address: @configure_form.ip_addr_single).save
        flash[:success] = "IPaddress is created"
        redirect_to config_path
        return
      end

    elsif not @configure_form.ip_addr_start.blank? and not @configure_form.ip_addr_end.blank?
      if is_valid_range(@configure_form.ip_addr_start, @configure_form.ip_addr_end)
        each_ip_addr(@configure_form.ip_addr_start, @configure_form.ip_addr_end) do |addr|
          AvailableIpAddress.create!(ip_address: addr) 
        end
        flash[:success] = "IPaddresses are created"
        redirect_to config_path
        return
      else
        flash[:failure] = "invalid range"
      end

    else 
      flash[:failure] = "text fields are blank"
    end

    @addresses = AvailableIpAddress.all
    render 'configure'
  end

  def destroy
    AvailableIpAddress.find(params[:id]).destroy
    flash[:success] = "Usage destroyed."
    redirect_to config_path
  end
 
  private
    def user_params
      params.require(:available_ip_address).permit(:ip_address, :ip_addr_single, 
                                                   :ip_addr_start, :ip_addr_end)
    end

    def are_single_and_range_forms_filled(configure_form)
      not configure_form.ip_addr_single.blank? and 
        (not configure_form.ip_addr_start.blank? or not configure_form.ip_addr_end.blank?)
    end

    # IPv4を想定
    def is_valid_range(addr_start, addr_end)
      if(AvailableIpAddress.new(ip_address: addr_start).valid? and AvailableIpAddress.new(ip_address: addr_end).valid?)
        start_arr = addr_start.split('.').map { |i| i.to_i } 
        end_arr = addr_end.split('.').map { |i| i.to_i }
        if(start_arr[0] == end_arr[0] && start_arr[1] == end_arr[1] && start_arr[2] == end_arr[2] && 
           start_arr[3] < end_arr[3])
          return true
        end
      end

      return false
    end
    
    def each_ip_addr(addr_start, addr_end, &block)
      start_arr = addr_start.split('.').map { |i| i.to_i } 
      end_arr = addr_end.split('.').map { |i| i.to_i }
      start_arr[3].upto(end_arr[3]) do |n|
        yield ("#{start_arr[0]}.#{start_arr[1]}.#{start_arr[2]}.#{n}")
      end
    end

  # end private
end

app/controllers/ip_addr_usages_controller.rb
class IpAddrUsagesController < ApplicationController
  def index
    @usages = IpAddrUsage.all
  end

  def new
    @usage = IpAddrUsage.new
    @unused_addr_map = AvailableIpAddress.unused.map { |addr| [addr.ip_address, addr.id] }
  end

  def create
    @usage = IpAddrUsage.new(user_params)
    @usage.available_ip_address = AvailableIpAddress.find(@usage.available_ip_address_id)
    if @usage.save
      flash[:success] = "Usage is created"
      redirect_to root_path
    else
      @unused_addr_map = AvailableIpAddress.unused.map { |addr| [addr.ip_address, addr.id] }
      render 'new'
    end
  end

  def edit
    @usage = IpAddrUsage.find(params[:id])
  end

  def update
    @usage = IpAddrUsage.find(params[:id])
    if @usage.update_attributes(user_params)
      flash[:success] = "Usage updated."
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @usage = IpAddrUsage.find(params[:id]).destroy
    flash[:success] = "Usage destroyed."
    redirect_to root_path
  end
 
  private
    def user_params
      params.require(:ip_addr_usage).permit(:available_ip_address_id , :user,
                                            :machine_name,
                                            :location, :note)
    end
  # end private
end

app/controllers/ip_address_controller.rb
class IpAddressController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "IPManagement"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/available_ip_addresses_helper.rb
module AvailableIpAddressesHelper
end

app/helpers/ip_addr_usages_helper.rb
module IpAddrUsagesHelper
end

app/views/available_ip_addresses/configure.html.erb
<h1>利用可能IPアドレスの範囲設定</h1>

<h2>IPアドレスの追加</h2>
<div class="row">
  <div class="span6 offset3">
    <%= form_for @configure_form, url: available_ip_addresses_path, action: "create" do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :ip_addr_single, "1つだけ追加" %>
      <%= f.text_field :ip_addr_single, class: "span3" %>

      <%= f.label :ip_addr_start, "範囲を指定して追加" %>
      <%= f.label :ip_addr_start, "例: 192.168.15.10 ~ 192.168.15.20" %>
      <%= f.text_field :ip_addr_start, class: "span3" %>
      ~
      <%= f.text_field :ip_addr_end, class: "span3" %>

      <%= f.submit "Create new IP address", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>


<h2>利用可能IPアドレスの一覧</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>IPアドレス</th>
      <th>利用者</th>
      <th>位置</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @addresses.sort.each do |address| %>
      <tr>
        <td><%= address.ip_address %></td>
        <td><%= address.ip_addr_usage.user unless address.ip_addr_usage.nil? %></td>
        <td><%= address.ip_addr_usage.location unless address.ip_addr_usage.nil? %></td>
        <td><% if address.ip_addr_usage.nil? %>
              <%= link_to "delete", address, method: :delete,
              data: { confirm: "このIPアドレスを一覧から削除します。本当によろしいですか？" } %>
            <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ip_addr_usages/edit.html.erb
<h1>IPアドレス利用状況の編集</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@usage) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :ip_address_str, "IPアドレス : #{@usage.ip_address}" %>

      <%= f.label :user, "利用者" %>
      <%= f.text_field :user %>

      <%= f.label :machine_name, "マシン名" %>
      <%= f.text_field :machine_name %>

      <%= f.label :location, "位置" %>
      <%= f.text_field :location %>

      <%= f.label :note, "備考" %>
      <%= f.text_area :note %>
      <p>
        <span class="left">
          <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
        </span>
        <span class='right'>
          <%= button_to "Cancel", root_path, class: "btn btn-large btn-warning", method: "get" %>
        </span>
      </p>
    <% end %>
  </div>
</div>

app/views/ip_addr_usages/index.html.erb
<h1>割り当て済みIPアドレス</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>IPアドレス</th>
      <th>利用者</th>
      <th>マシン名</th>
      <th>位置</th>
      <th>備考</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @usages.sort.each do |usage| %>
      <tr class="<%= usage.status %>">
        <td><%= link_to usage.ip_address, edit_ip_addr_usage_path(usage) %></td>
        <td><%= usage.user %></td>
        <td><%= usage.machine_name %></td>
        <td><%= usage.location %></td>
        <td><%= usage.note %></td>
        <td><%= link_to "delete", usage, method: :delete,
          data: { confirm: "割り当てを解除します。本当によろしいですか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ip_addr_usages/new.html.erb
<h1>IPアドレスの割り当て</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@usage) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :available_ip_address_id , "IPアドレス" %>
      <%= f.select :available_ip_address_id, @unused_addr_map  %>

      <%= f.label :user, "利用者" %>
      <%= f.text_field :user %>

      <%= f.label :machine_name, "マシン名" %>
      <%= f.text_field :machine_name %>

      <%= f.label :location, "位置" %>
      <%= f.text_field :location %>

      <%= f.label :note, "備考" %>
      <%= f.text_area :note %>

      <%= f.submit "Create new usage", class: "btn btn-large btn-primary" %>

    <% end %>
    <%= button_to "Cancel", root_path, class: "btn btn-large btn-warning", method: "get" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
  <div class="container">
    <%= link_to "ip_management", root_path, id: "logo" %>
    <nav>
    <ul class="nav pull-right">
      <li><%= link_to "index",    root_path %></li>
      <li><%= link_to "割り当て", new_ip_addr_usage_path %></li>
      <li><%= link_to "設定", config_path %></li>
    </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title))%></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% error_object = @usage || @configure_form %>
<% if error_object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(error_object.errors.count, "error") %>.
    </div>
    <ul>
      <% error_object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/unreachable_addr_notifier/send_notification.text.erb
IP管理アプリに登録されている以下のIPアドレスは、一定期間の間応答がありませんでした。
管理者の方は登録情報の更新をよろしくお願いします。

==============================

<% @unreachable_usages.each do |usage| %>
  <%= "IPアドレス: #{usage.ip_address}, 利用者: #{usage.user}, 位置: #{usage.location}, 応答がない日数: #{usage.ping_failure_count}" %>
<% end %>